name: Update the list
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '16 20,2 * * *'
  workflow_dispatch:
jobs:
  mklist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Build list
      run: |
        echo 0 > "status.txt" 
        pip3 install requests
        python compile.py
        echo 1 > "status.txt"
    - name: Commit & Push
      uses: actions-x/commit@v4
      with:
          email: updatebot@iam-py-test.github.io
          name: Update bot
          branch: main
          message: Update the list
